#Задать значения полей
First_name = 'Иван'
Last_name = 'Петров'
Address = 'Ленина, 55-3'
Zip_code = ''
City = 'Москва'
Country = 'Россия'
Email = 'test@skypro.com'
Phone_number = '+7985899998787'
Job_position = 'QA'
Company = 'SkyPro'